; =============================================================================
; SMART NURSERY SYSTEM — platformio.ini
; =============================================================================
; Two environments, two separate source files.
;
; To flash the MAIN ESP:
;   1. Select "env:main" in the PlatformIO toolbar (bottom of VS Code)
;   2. Click Upload (→)
;
; To flash the SLAVE ESP:
;   1. Select "env:slave" in the PlatformIO toolbar
;   2. Click Upload (→)
; =============================================================================

; ===== UPLOAD INSTRUCTIONS BY TERMINAL =====
; pio run -e main -t upload
; pio run -e slave -t upload

; ===== MONITOR INSTRUCTIONS =====
; pio device monitor -e main
; pio device monitor -e slave

; ===== UPLOADFS INSTRUCTIONS =====
; pio run -e main -t uploadfs


[env:main]
platform    = espressif32
board       = esp32doit-devkit-v1
framework   = arduino
monitor_speed = 115200
; upload_speed = 115200
src_filter    = +<main.cpp>
lib_deps    = 
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.9
	adafruit/RTClib@1.14.2
    claws/BH1750
    bblanchon/ArduinoJson@^7.4.1
    me-no-dev/ESPAsyncWebServer@^1.2.3
board_build.filesystem = littlefs

[env:slave]
platform    = espressif32
board       = esp32doit-devkit-v1
framework   = arduino
monitor_speed = 115200
; upload_speed = 115200
src_filter    = +<slave.cpp>
lib_deps    = 
    adafruit/Adafruit Unified Sensor@^1.1.9
    bblanchon/ArduinoJson@^7.4.1
board_build.filesystem = littlefs
